### PR TITLE
FreeBSD 12 support

### PR DESCRIPTION
**Pull request by kirillrdy**
this is similar to @joegsn approach from #150 but also ensures FreeBSD 11 and most importantly OSX are not broken

### CODE REVIEW

**Comment by kirillrdy** [comment]
hmm, doesn't actually work ... need more testing

**Comment by kirillrdy** [comment]
@sparkymat give it a test. Should be all good now

**Comment by courtland** [comment]
I'm also interested in this patch or some form of it making its way into the official gem. For now I have accepted this pull request into my own fork. It works for my environment under macOS, FreeBSD-10.1-RELEASE, FreeBSD-11.1-RELEASE, and FreeBSD-12.0-CURRENT.

FreeBSD 12 is indeed not slated to come out until late October / early November 2018, but in my case I have a rails app that must be vetted against FreeBSD-CURRENT in time for its release and bcrypt compilation is one of the road blocks.

It looks like FreeBSD has already adopted some form of this patch in the ports tree.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212304

**Comment by kirillrdy** [comment]
I've rebased against latest master and applied patches similar to
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212304

Let me know what you guys think

**Comment by tjschuck** [comment]
Both of your final changes are in the vendored C implementation that this library uses — please propose them upstream at https://www.openwall.com/crypt/, and then they can be pulled downstream into bcrypt-ruby.

Thanks!

**Comment by solardiz** [comment]
Someone posted this PR's URL as a "Quick Comment" at https://www.openwall.com/crypt/ so I just took a look. To me, the weirdest thing is that you're apparently trying to use this wrapper code intended for use inside a libc in a project that isn't a libc. That's why you're running into issues. Perhaps you should be using crypt_blowfish's native interfaces and not the wrappers.

**Comment by tymat** [comment]
This has not been fixed.

**Pull request closed without merging**
