### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dfredell**
Add the prerequisite install of ruby-sdk so the system has header files.

### CODE REVIEW

**Comment by tjschuck** [comment]
I don't think this is necessary — if it is, I'd be shocked that this is the first we'd ever heard about it.

There doesn't even seem to be an Ubuntu package named ruby-sdk in any of the suites: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=ruby-sdk&searchon=names

**Comment by dfredell** [comment]
@tjschuck you are absolutely correct there is no `ruby-sdk` that was my mistake. bcrypt requires `ruby-dev`. I'm new to ruby, and I needed to build a project. Maybe it is totally common for people to `sudo apt install ruby-dev` and not just `sudo apt install ruby`

Here is an example, I did `sudo apt uninstall ruby; sudo apt autoremove; sudo rm -rf /var/lib/gems/2.5.0/gems/bcrypt-*` then tried installing bcrypt again. 

```
danfredell@bender ~/W/C/website-main> sudo gem install bcrypt
[sudo] password for danfredell: 
Building native extensions. This could take a while...
ERROR:  Error installing bcrypt:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/bcrypt-3.1.12/ext/mri
/usr/bin/ruby2.5 -r ./siteconf20180725-10953-1lowuwj.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/bcrypt-3.1.12 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/bcrypt-3.1.12/gem_make.out
danfredell@bender ~/W/C/website-main> sudo apt install ruby-sdk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ruby-sdk
danfredell@bender ~/W/C/website-main> sudo apt install ruby-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgmp-dev libgmpxx4ldbl ruby2.5-dev ruby2.5-doc
Suggested packages:
  gmp-doc libgmp10-doc libmpfr-dev
The following NEW packages will be installed:
  libgmp-dev libgmpxx4ldbl ruby-dev ruby2.5-dev ruby2.5-doc
0 upgraded, 5 newly installed, 0 to remove and 44 not upgraded.
Need to get 2,199 kB of archives.
After this operation, 20.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 libgmpxx4ldbl amd64 2:6.1.2+dfsg-2 [8,964 B]
Get:2 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 libgmp-dev amd64 2:6.1.2+dfsg-2 [316 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 ruby2.5-dev amd64 2.5.1-1ubuntu1 [63.7 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 ruby-dev amd64 1:2.5.1 [4,604 B]
Get:5 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 ruby2.5-doc all 2.5.1-1ubuntu1 [1,806 kB]
Fetched 2,199 kB in 0s (4,630 kB/s)    
Selecting previously unselected package libgmpxx4ldbl:amd64.
(Reading database ... 381464 files and directories currently installed.)
Preparing to unpack .../libgmpxx4ldbl_2%3a6.1.2+dfsg-2_amd64.deb ...
Unpacking libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-2) 
Selecting previously unselected package libgmp-dev:amd64
Preparing to unpack .../libgmp-dev_2%3a6.1.2+dfsg-2_amd64.deb
Unpacking libgmp-dev:amd64 (2:6.1.2+dfsg-2) 
Selecting previously unselected package ruby2.5-dev:amd64 
Preparing to unpack .../ruby2.5-dev_2.5.1-1ubuntu1_amd64.deb 
Unpacking ruby2.5-dev:amd64 (2.5.1-1ubuntu1)
Selecting previously unselected package ruby-dev:amd64
Preparing to unpack .../ruby-dev_1%3a2.5.1_amd64.deb 
Unpacking ruby-dev:amd64 (1:2.5.1) 
Selecting previously unselected package ruby2.5-doc
Preparing to unpack .../ruby2.5-doc_2.5.1-1ubuntu1_all.deb
Unpacking ruby2.5-doc (2.5.1-1ubuntu1)
Processing triggers for libc-bin (2.27-3ubuntu1)
Setting up ruby2.5-doc (2.5.1-1ubuntu1)
Setting up libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-2) 
Setting up libgmp-dev:amd64 (2:6.1.2+dfsg-2) 
Setting up ruby2.5-dev:amd64 (2.5.1-1ubuntu1) 
Setting up ruby-dev:amd64 (1:2.5.1)
Processing triggers for libc-bin (2.27-3ubuntu1) 
danfredell@bender ~/W/C/website-main> sudo gem install bcrypt 
Building native extensions. This could take a while...
Successfully installed bcrypt-3.1.12
Parsing documentation for bcrypt-3.1.12
Done installing documentation for bcrypt after 0 seconds
1 gem installed                   
danfredell@bender ~/W/C/website-main> 
```

**Comment by tjschuck** [comment]
I think it's actually most common for people to install Ruby using a version manager like [rbenv](https://github.com/rbenv/rbenv), [chruby](https://github.com/postmodern/chruby), [rvm](https://rvm.io), etc.  That seems to even be the official recommendation on https://www.ruby-lang.org/en/downloads/ at this point.

If you wanted to use your OS's package manager, two things of note per the official installation instructions for Ruby at https://www.ruby-lang.org/en/documentation/installation/#package-management-systems:

1. You should install `ruby-full`, not just `ruby`, which [includes `ruby-dev`](https://packages.ubuntu.com/bionic/ruby-full).

2. They seem to generally _not_ recommend installing from your OS package manager (nor do I), because you'll likely get an out of date version.

I personally use rbenv and recommend it, but pick your poison!

That said, since just apt-installing the `ruby` package like you did isn't a recommended way to install Ruby, I don't think this needs to be added to the bcrypt-ruby installation instructions particularly.

Hope those links above help!  Welcome to Ruby!

**Comment by dfredell** [comment]
@tjschuck That is fantastic info. Thank you for putting in the effort and for a quick response. My feelings towards the ruby community is very positive. 
I agree the bcrypt-ruby install instructions don't need to change.

**Pull request closed without merging**
