### PR TITLE
Add ruby 2.7 to the test matrix and attempt to fix travis

### PR DESCRIPTION
**Pull request by agrare**
Travis runs appear to be failing while installing bundler: https://travis-ci.org/github/codahale/bcrypt-ruby/jobs/710497526

### CODE REVIEW

**Comment by tenderlove** [comment]
Maybe we should switch to GitHub Actions?

**Comment by Fryguy** [comment]
Not sure why the Gemfile.lock is committed in a library

**Comment by tenderlove** [comment]
> Not sure why the Gemfile.lock is committed in a library

I'm not either.  I think I just kept it because it was already there.  I think we should remove it though.

**Comment by tenderlove** [comment]
I guess it was added in bbbba5633e3b2b7c7fb30045b60d0b953c32e225.  Lets remove it.

**Pull request merged**
